# This is a basic workflow to help you get started with Actions

name: Build Vue

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev-front ]
  pull_request:
    branches: [ dev-front ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'allinu'
        reponame: 'OAO'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
